site_name: Buds ECS Library
docs_dir: docs
site_description: "Documentation for the Buds Entity-Component-System library written completely in python"

theme:
  name: material

nav:
  - Home: index.md
  - Tutorials: 
    - Getting Started: tutorials/start.md
    - Custom Trait Base: tutorials/custom_trait.md
  - API:
      - Core: api/base.md
      - System: api/system.md
      - Itertools: api/itertools.md
      - Seeds: api/seeds.md
      - World Implementations:
        - Archetypes: api/worlds/archetypes.md
        - Sparse: api/worlds/sparse.md
      - Extras:
        - numpy: api/extras/numpy.md
plugins:
  - search
  - mkdocstrings